import { Smartphone, Usb, Wifi } from 'lucide-react'
import type { Device } from '../data'
import type { Connection } from '../types'

export function Onboarding({ state, device, desktop, onDetect, onPair, onCancel }: { state: Exclude<Connection, 'connected'>; device: Device; desktop: boolean; onDetect: () => void; onPair: () => void; onCancel: () => void }) {
  if (state === 'none') return <div className="onboarding"><div className="scan-icon"><i /><i /><span><Smartphone size={31} /></span></div><h2>No device connected</h2><p>Connect an iPhone or iPad over USB or make it available on the local network. idevice is scanning usbmuxd and Bonjour.</p><code><i />usbmuxd · mobdev2 · RemotePairing</code><button className="primary-button" onClick={onDetect}><Usb size={16} />{desktop ? 'Scan again' : 'Simulate USB connection'}</button><div className="steps"><span className="active">Detect</span><i /><span>Trust</span><i /><span>Ready</span></div></div>
  if (device.connectable === false) return <div className="onboarding"><span className="detected-icon"><Wifi size={31} /><i>!</i></span><h2>{device.name} found on the network</h2><p>Bonjour can see this device, but no paired Lockdown route is available yet.</p><div className="trust-card card"><p><b>1</b><span>Connect the device with a <strong>USB data cable</strong></span></p><p><b>2</b><span>Unlock it and tap <strong>Trust</strong> when prompted</span></p></div><button className="primary-button full-button" onClick={onDetect}>Check connections again</button><button className="text-button" onClick={onCancel}>Cancel</button></div>
  return <div className="onboarding"><span className="detected-icon"><Smartphone size={31} /><i>!</i></span><h2>{device.model} detected</h2><p>Trust this computer to open a lockdown session.</p><div className="trust-card card"><p><b>1</b><span>Tap <strong>Trust</strong> on the device prompt</span></p><p><b>2</b><span>Enter the device passcode</span></p><div className="passcode"><i>•</i><i>•</i><i>•</i><i /></div></div><button className="primary-button full-button" onClick={onPair}>Trust & generate pairing</button><button className="text-button" onClick={onCancel}>Cancel</button></div>
}
